-- Accounts and everything that proves who someone is.
--
-- No password column exists anywhere in this schema, and that is the point:
-- sign-in is delegated to Google and GitHub, so there is no credential here to
-- leak, reset, or brute force.
create schema if not exists identity;

create table identity.accounts (
    id           uuid        primary key,
    email        text        not null,       -- always a VERIFIED address (see AccountService)
    display_name text,
    avatar_url   text,
    status       text        not null default 'active'
                 check (status in ('active', 'suspended', 'deleted')),
    created_at   timestamptz not null default now(),
    updated_at   timestamptz not null default now(),
    deleted_at   timestamptz
);

-- Case-insensitive uniqueness without the citext extension: Railway's managed
-- Postgres does not guarantee superuser, and `create extension` needs it.
-- Application code lowercases before writing; this index enforces it.
create unique index accounts_email_lower_uk on identity.accounts (lower(email));

-- One row per linked identity provider. An account may have both Google and
-- GitHub pointing at it.
create table identity.identities (
    id               uuid        primary key,
    account_id       uuid        not null references identity.accounts (id) on delete cascade,
    provider         text        not null check (provider in ('google', 'github')),
    provider_user_id text        not null,   -- Google `sub` / GitHub numeric id.
                                             -- NEVER the email: addresses change hands,
                                             -- and reusing one would hand over an account.
    email_at_link    text,
    created_at       timestamptz not null default now(),
    last_login_at    timestamptz,
    unique (provider, provider_user_id)
);

create index identities_account_idx on identity.identities (account_id);

-- Desktop installs. Per-install, not per-machine: the app is portable and the
-- same install legitimately runs from a USB stick on several machines.
create table identity.devices (
    id            uuid        primary key,
    account_id    uuid        not null references identity.accounts (id) on delete cascade,
    install_id    text        not null,      -- random UUID generated by the desktop app
    name          text,                      -- "DESKTOP-4F2K - Windows"
    app_version   text,
    first_seen_at timestamptz not null default now(),
    last_seen_at  timestamptz not null default now(),
    revoked_at    timestamptz,
    unique (account_id, install_id)
);

-- Browser sessions AND desktop access tokens, deliberately one table: both are
-- "an opaque bearer credential that maps to an account", and one lookup path
-- means one place to get revocation right.
--
-- Only the SHA-256 of the token is stored, so a database leak does not hand out
-- live sessions.
create table identity.sessions (
    id           uuid        primary key,
    account_id   uuid        not null references identity.accounts (id) on delete cascade,
    kind         text        not null check (kind in ('web', 'desktop')),
    token_hash   bytea       not null unique,
    device_id    uuid        references identity.devices (id) on delete cascade,
    user_agent   text,
    ip           text,
    created_at   timestamptz not null default now(),
    last_seen_at timestamptz not null default now(),
    expires_at   timestamptz not null,
    revoked_at   timestamptz
);

create index sessions_account_idx on identity.sessions (account_id);
create index sessions_expiry_idx  on identity.sessions (expires_at) where revoked_at is null;

-- Long-lived desktop credentials, rotated on every use. `family_id` groups a
-- rotation chain: replaying a token that has already been rotated revokes the
-- whole family, which is the standard detection for a stolen refresh token.
create table identity.refresh_tokens (
    id          uuid        primary key,
    account_id  uuid        not null references identity.accounts (id) on delete cascade,
    device_id   uuid        references identity.devices (id) on delete cascade,
    token_hash  bytea       not null unique,
    family_id   uuid        not null,
    issued_at   timestamptz not null default now(),
    expires_at  timestamptz not null,
    revoked_at  timestamptz,
    replaced_by uuid        references identity.refresh_tokens (id)
);

create index refresh_tokens_family_idx  on identity.refresh_tokens (family_id);
create index refresh_tokens_account_idx on identity.refresh_tokens (account_id);
